fixup

diff --git a/.github/workflows/debian-builder-workflow.yaml b/.github/workflows/debian-builder-workflow.yaml
--- a/.github/workflows/debian-builder-workflow.yaml
+++ b/.github/workflows/debian-builder-workflow.yaml
@@ -147,25 +147,45 @@ jobs:
       - name:  Docker image cache
         uses: actions/cache@v1
         with:
-          path: ~/.docker-images
+          path: ~/docker-images
           key: ${{ matrix.osVersionCodename}}-${{ matrix.architecture }}
 
       - name:  Build Docker image
+        # If a script fails, the image cache gets erased.  To work
+        # around this, always succeed and detect the failure in the
+        # next job.
+        id: build_docker_img
         env:
           TAG: '${{ matrix.architecture }}_${{ matrix.osVersionNumber }}'
         working-directory: ./build/machinekit-hal
         run: |
-          test ! -d ~/.docker-images || ls -l ~/.docker-images
-          if test -f ~/.docker-images/image; then
-              docker load -i ~/.docker-images/image
+          test ! -d ~/docker-images || ls -l ~/docker-images
+          if test -f ~/docker-images/image; then
+              docker load -i ~/docker-images/image
           fi
-          scripts/build_debian_docker_image -r temp -i temp -t ${TAG}
-          mkdir -p ~/.docker-images
-          docker save -o ~/.docker-images/image temp/temp:${TAG}
-          test ! -d ~/.docker-images || ls -l ~/.docker-images
+          mkdir -p ~/docker-images
+          if scripts/build_debian_docker_image -r temp -i temp -t ${TAG}; then
+              mkdir -p ~/docker-images
+              docker save -o ~/docker-images/image temp/temp:${TAG}
+              echo ::set-output name=res::$?
+          else
+              touch ~/docker-images/image
+              echo ::set-output name=res::1
+          fi
+          ls -l ~/docker-images
 
-  buildMachinekitHALDebianPackages:
-    name: MK HAL pkgs ${{ matrix.osVersionCodename }}-${{ matrix.architecture }}
+      - name:  Store Docker image artifact
+        uses: actions/upload-artifact@v1
+        with:
+          name: docker-images
+          path: image
+
+    outputs:
+      DockerBuildRes: ${{ steps.build_docker_img.outputs.res }}
+
+
+  buildHALDebianPackages:
+    name: HAL pkgs ${{ matrix.osVersionCodename }}-${{ matrix.architecture }}
     runs-on: ubuntu-latest
     needs: buildDockerImage
     strategy:
@@ -176,6 +196,10 @@ jobs:
       DOCKER_IMAGE: 'temp/temp'
     
     steps:
+      - name: Check Docker build result
+        run: |
+          test "${{ needs.buildDockerImage.outputs.DockerBuildRes }}" = 0
+
       - name: Clone MK-HAL repository
         uses: actions/checkout@v2
         with:
@@ -185,12 +209,12 @@ jobs:
       - name:  Docker image cache
         uses: actions/cache@v1
         with:
-          path: ~/.docker-images
+          path: ~/docker-images
           key: ${{ matrix.osVersionCodename}}-${{ matrix.architecture }}
 
       - name:  Load Docker image
         run: |
-          docker load -i ~/.docker-images/image
+          docker load -i ~/docker-images/image
 
       - name: Build MK-HAL package
         working-directory: ./build/machinekit-hal  
